import { useState, useCallback } from 'react';
import { ThumbsUp, ThumbsDown, Copy, Check, Download, FileText, File } from 'lucide-react';
import { submitFeedback } from '../api';

// ── Derive filename from collection + datetime ───────────────────────
function buildFilename(collection, workspaceId) {
  const source = collection
    ? collection.replace(/\s+/g, '_')
    : workspaceId
    ? 'Workspace'
    : 'ChemIQ';
  const now = new Date();
  const date = now.toISOString().slice(0, 10);                        // 2026-03-06
  const time = now.toTimeString().slice(0, 5).replace(':', '-');      // 10-38
  return `${source}_${date}_${time}`;
}

// ── Markdown → plain text ─────────────────────────────────────────────
function markdownToPlain(md) {
  return md
    .replace(/#{1,6}\s+/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`{1,3}([\s\S]*?)`{1,3}/g, '$1')
    .replace(/>\s+/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/^\d+\.\s+/gm, '')
    .trim();
}

// ── Download as .doc (Word-compatible RTF) ────────────────────────────
function downloadAsWord(question, answer, sources, collection, workspaceId) {
  const plain = markdownToPlain(answer);
  const sourceLines = sources?.length
    ? '\n\nSources:\n' + sources.map(s => `  • ${s.source || s.id} (${(s.score * 100).toFixed(0)}%)`).join('\n')
    : '';

  // RTF format — opens natively in Word with proper formatting
  const rtf = `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0 Arial;}}
{\\colortbl ;\\red27\\green58\\blue107;}
\\f0\\fs24
{\\b\\fs28\\cf1 Question}\\par
\\par
${question.replace(/[\\{}]/g, '\\$&')}\\par
\\par
{\\b\\fs28\\cf1 Answer}\\par
\\par
${plain.replace(/[\\{}]/g, '\\$&').replace(/\n/g, '\\par\n')}
${sourceLines ? `\\par\\par{\\b\\fs26\\cf1 Sources}\\par\\par${sourceLines.replace(/[\\{}]/g, '\\$&').replace(/\n/g, '\\par\n')}` : ''}
\\par\\par
{\\fs18\\cf1 Generated by ChemIQ · Chemical Document Intelligence}
}`;

  const blob = new Blob([rtf], { type: 'application/rtf' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${buildFilename(collection, workspaceId)}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Download as PDF using jsPDF ───────────────────────────────────────
async function downloadAsPDF(question, answer, sources, collection, workspaceId) {
  const { jsPDF } = await import('jspdf');
  const doc   = new jsPDF({ unit: 'pt', format: 'a4' });
  const W     = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentW = W - margin * 2;
  let y = 56;

  const navy  = [27, 58, 107];
  const black = [17, 24, 39];
  const grey  = [107, 114, 128];

  // Header bar
  doc.setFillColor(...navy);
  doc.rect(0, 0, W, 36, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text('ChemIQ  ·  Chemical Document Intelligence', margin, 23);

  // Date top-right
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(200, 215, 230);
  doc.text(new Date().toLocaleString(), W - margin, 23, { align: 'right' });

  y = 60;

  // Section: Question
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...navy);
  doc.text('Question', margin, y);
  y += 6;
  doc.setDrawColor(...navy);
  doc.setLineWidth(0.5);
  doc.line(margin, y, W - margin, y);
  y += 14;

  // Question text in a shaded box
  const qLines = doc.setFont('helvetica', 'normal').setFontSize(10.5)
    .splitTextToSize(question, contentW - 16);
  const qBoxH = qLines.length * 14 + 16;
  doc.setFillColor(238, 242, 248);
  doc.roundedRect(margin, y, contentW, qBoxH, 4, 4, 'F');
  doc.setTextColor(...black);
  doc.text(qLines, margin + 10, y + 13);
  y += qBoxH + 22;

  // Section: Answer
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...navy);
  doc.text('Answer', margin, y);
  y += 6;
  doc.line(margin, y, W - margin, y);
  y += 14;

  // Answer text
  const plain  = markdownToPlain(answer);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(...black);
  const aLines = doc.splitTextToSize(plain, contentW);
  const pageH  = doc.internal.pageSize.getHeight();

  for (const line of aLines) {
    if (y > pageH - 60) {
      doc.addPage();
      y = 48;
    }
    doc.text(line, margin, y);
    y += 14;
  }

  // Section: Sources
  if (sources?.length) {
    y += 10;
    if (y > pageH - 80) { doc.addPage(); y = 48; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...navy);
    doc.text('Sources', margin, y);
    y += 6;
    doc.line(margin, y, W - margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...grey);
    for (const s of sources) {
      if (y > pageH - 48) { doc.addPage(); y = 48; }
      doc.text(`• ${s.source || s.id}  (${(s.score * 100).toFixed(0)}% match)`, margin + 8, y);
      y += 14;
    }
  }

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(8.5);
    doc.setTextColor(...grey);
    doc.text(`Generated by ChemIQ`, margin, pageH - 20);
    doc.text(`Page ${p} of ${totalPages}`, W - margin, pageH - 20, { align: 'right' });
  }

  doc.save(`${buildFilename(collection, workspaceId)}.pdf`);
}

// ── Main component ────────────────────────────────────────────────────
export default function MessageActions({
  question,
  answer,
  sources,
  collection,
  workspaceId,
  conversationId,
}) {
  const [rating, setRating]         = useState(null);
  const [copied, setCopied]         = useState(false);
  const [showDl, setShowDl]         = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const handleRating = useCallback(async (value) => {
    if (rating || submitting) return;
    setRating(value);
    setSubmitting(true);
    try {
      await submitFeedback({
        query:           question,
        answer,
        rating:          value,
        sources:         sources || [],
        collection:      collection || null,
        workspace_id:    workspaceId || null,
        conversation_id: conversationId || null,
      });
    } catch { /* silent */ }
    finally { setSubmitting(false); }
  }, [rating, submitting, question, answer, sources, collection, workspaceId, conversationId]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(answer).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [answer]);

  return (
    <div className="message-actions">
      <button
        className={`msg-action-btn${rating === 'up'   ? ' active-up'   : ''}`}
        onClick={() => handleRating('up')}
        disabled={!!rating}
        title="Good response"
      >
        <ThumbsUp size={13} />
      </button>
      <button
        className={`msg-action-btn${rating === 'down' ? ' active-down' : ''}`}
        onClick={() => handleRating('down')}
        disabled={!!rating}
        title="Bad response"
      >
        <ThumbsDown size={13} />
      </button>

      <div className="msg-action-divider" />

      <button
        className={`msg-action-btn${copied ? ' active-up' : ''}`}
        onClick={handleCopy}
        title={copied ? 'Copied!' : 'Copy answer'}
      >
        {copied ? <Check size={13} /> : <Copy size={13} />}
      </button>

      <div className="msg-action-dropdown-wrap">
        <button
          className="msg-action-btn"
          onClick={() => setShowDl(v => !v)}
          title="Download answer"
        >
          <Download size={13} />
        </button>
        {showDl && (
          <div className="msg-action-dropdown" onMouseLeave={() => setShowDl(false)}>
            <button
              className="msg-dl-option"
              onClick={() => { downloadAsWord(question, answer, sources, collection, workspaceId); setShowDl(false); }}
            >
              <FileText size={13} /> Download as Word
            </button>
            <button
              className="msg-dl-option"
              onClick={() => { downloadAsPDF(question, answer, sources, collection, workspaceId); setShowDl(false); }}
            >
              <File size={13} /> Download as PDF
            </button>
          </div>
        )}
      </div>

      {rating && (
        <span className="msg-action-thanks">
          {rating === 'up' ? '👍 Thanks!' : '👎 Noted'}
        </span>
      )}
    </div>
  );
}
